### PR TITLE
Add Limiter interface

### PR DESCRIPTION
**Pull request by vmihailenco**
This is an alternative to https://github.com/go-redis/redis/pull/874. Basically it defines rate limiter interface which allows to implement different limiting strategies in separate packages.

@xianglinghui what do you think? Is provided API enough to cover your needs? I am aware that code like https://github.com/go-redis/redis/blob/master/ring.go#L618-L621 requires some work in go-redis, but other than that it seems to be enough.

### CODE REVIEW

**Comment by xianglinghui** [comment]
@vmihailenco Yes, this way can meet my needs. The rate limiter is implemented by myself and specified at Options.

The Limiter API may need node address param, because rate limit is for problem node, not for the whole cluster, like this:
type Limiter interface {
	Take(addr string) error
	Put(addr string, err error)
}

**Comment by vmihailenco** [comment]
Can't you create a separate Limiter for each node?

**Comment by xianglinghui** [comment]
@vmihailenco Ah, I misunderstood, I thought there is just one instance of  Limiter for a cluster client before.

When a problem node is limited by the Limiter, we may need print the address of it to log, then we can locate problem faster.

So Limiter may need an API to set the info of node which the limiter has stand for.

**Comment by xianglinghui** [comment]
@vmihailenco yes，I think this way can work. The api "redis_limiter.New" just pass an address of the node, I think will be more better.

**Comment by vmihailenco** [comment]
Okay, updated the PR

**Comment by xianglinghui** [comment]
@vmihailenco Will you add Limiter to ClusterClient? The PR seems just support Client.

**Comment by xianglinghui** [comment]
@vmihailenco yes，I think it is great.

**Comment by vmihailenco** [comment]
Okay, added `OnNewNode` option.

**Comment by xianglinghui** [comment]
@vmihailenco It is great, thanks very much!

**Comment by vmihailenco** [comment]
Thank you! Do you think we can/should merge this PR?

**Comment by xianglinghui** [comment]
@vmihailenco yes.

**Comment by xianglinghui** [comment]
@vmihailenco Does this feature will merge into master branch?

**Comment by vmihailenco** [comment]
Yes, sorry - I am just not quite happy with interface. Probably following is better:

```
type Limiter interface {
    // Allow return a nil if operation is allowed or an error otherwise.
    // If operation is allowed client must report the result of operation
    // whether is a success or a failure.
    Allow() error
    // ReportResult reports the result of previously allowed operation.
    // nil error indicates a success, non-nil error indicates a failure.
    ReportResult(err error)
}
```

**Comment by xianglinghui** [comment]
@vmihailenco I have run a test for Limiter in my project，there have a bug in redis.go.

type baseClient struct {
	limiter  Limiter
	...
}
type Client struct {
	baseClient
	limiter Limiter
}
func (c *Client) SetLimiter(l Limiter) *Client {
	c.limiter = l
	return c
}

baseClient and Client both have "limiter" field, the c.limiter in SetLimiter will not point to baseClient's limiter，so SetLimiter will not set value to baseClient.limiter.

**Comment by vmihailenco** [comment]
Should be fixed thanks.

**Pull request merged**
