### PR TITLE
Handling of isPrefix in Reader.ReadLine.

### PR DESCRIPTION
**Pull request by dtucker2**
I've added a commit to resolve an issue where data greater than 4096 bytes could not be read without generating an error.

### CODE REVIEW

**Comment by vmihailenco** [comment]
What real use case this fixes? `SET` and `GET` already works for big strings.

**Comment by dtucker2** [comment]
I've encountered problems whilst receiving large messages on subscribed channels.

**Comment by vmihailenco** [comment]
Can you add a test that reproduces the problem?

**Comment by dtucker2** [comment]
If you mean through the PubSub code, probably. I've already written one for the Reader.

**Comment by vmihailenco** [comment]
Yes, for some public API. `Reader.ReadLine` is an internal API and it is not supposed to be used to read large strings.

**Comment by dtucker2** [comment]
Leave it with me, I'll see what I can do.

**Comment by dtucker2** [comment]
I implemented a test on the Subscribe method, however I believe I have been looking in the wrong place. It seems the problem may be the size of the net.Conn ReadBuffer, however I have still not tracked down where this is set.

**Comment by vmihailenco** [comment]
Closing - please reopen if you find the root cause of this.

**Pull request closed without merging**
