### PR TITLE
sync master

### PR DESCRIPTION
**Pull request by monkey92t**

### CODE REVIEW

**Comment by monkey92t** [comment]
This should be an unexpected test error.

**Comment by vmihailenco** [comment]
@monkey92t what do you mean? This error `interface conversion: *errors.errorString is not net.Error: missing method Temporary`?

**Review by vmihailenco — APPROVED** [review]

**Comment by monkey92t** [comment]
> @monkey92t what do you mean? This error `interface conversion: *errors.errorString is not net.Error: missing method Temporary`?

The `Read Timeout` test is affected by the `HELLO` command and I have fixed it.

**Comment by vmihailenco** [comment]
>Do you have any other questions?

Nope, thank you :+1:

**Pull request merged**
