### PR TITLE
fix retryTimeout in baseClient _process

### PR DESCRIPTION
**Pull request by ray2011**
Fix [issue 2070](https://github.com/go-redis/redis/issues/2070)

### CODE REVIEW

**Comment by ray2011** [comment]
@vmihailenco netErr.Tempoary is deprecated, and I found `allowTimeout` in `isBadConn` cant be true now, so I change it to false.

**Review by viciousstar — COMMENTED** [review]
just set a default value，eg 0？

**Review by viciousstar — COMMENTED** [review]
any net.Error except timeout err will retry?

**Comment by ray2011** [comment]
> just set a default value，eg 0？

Good advice. Has changed.

**Comment by ray2011** [comment]
> @vmihailenco netErr.Tempoary is deprecated, and I found `allowTimeout` in `isBadConn` cant be true now, so I change it to false.

revert this.

**Comment by vmihailenco** [comment]
Thanks

**Pull request merged**
