### PR TITLE
Backport wrapMultiExec() cmds copy bug fix from v8

### PR DESCRIPTION
**Pull request by wspowell**

### CODE REVIEW

**Comment by wspowell** [comment]
This is probably the same bug that was being hit in issue 1386.

**Comment by monkey92t** [comment]
We did not plan to fix v7 before, it will be very difficult, and we have removed `travis CI`

@vmihailenco What do you think?

**Comment by vmihailenco** [comment]
Since out time is limited, we don't support old versions. But we do accept backports from users if tests are passing.

So I think we should merge the first [commit](https://github.com/go-redis/redis/pull/1823/commits/193fcc450425655941982615d08e6e8201386db1), run tests locally (since travis is not working), release a new v7 version, and forget about it (i.e. don't try to fix build / backport other changes). Does that sound good?

**Comment by monkey92t** [comment]
Yes, I think this is a good idea, I have removed the extra.

**Comment by monkey92t** [comment]
I performed the test locally and found no problems, I will merge it and release a new version

**Comment by vmihailenco** [comment]
Thanks :+1:

**Pull request merged**
