### PR TITLE
Release redis.v3 beta.

### PR DESCRIPTION
**Pull request by vmihailenco**
@dim is there anything you want to do before releasing v3 with ClusterClient?

### CODE REVIEW

**Comment by dim** [comment]
Only a `Readonly bool` on the cluster options, which is then applied on `initConn`

**Comment by vmihailenco** [comment]
Looks like that can be added at any point and should not block v3. FYI I plan to tag v3 this weekend after I switch our internal projects to use new API.

**Comment by epelc** [comment]
@vmihailenco Does v2 of this package work with redis 3.0?

**Comment by vmihailenco** [comment]
Yes, it works. go-redis client version numeration has nothing to do with Redis Server version numeration. It is just an accident that they (will) match.

**Comment by epelc** [comment]
@vmihailenco Thanks I got a few more questions. Are there some major changes in v3? Would you recommend using v2 or v3 if I was going to switch from redigo today?

**Comment by vmihailenco** [comment]
I would say v3. It has nicer API and has Redis Cluster support.

**Pull request merged**
