### PR TITLE
ADD: RetryConditionFunc to options which allows the user to decide when to retry

### PR DESCRIPTION
**Pull request by git-hulk**

### CODE REVIEW

**Comment by vmihailenco** [comment]
What are you trying to achieve? What commands/errors do you want to retry?

**Comment by git-hulk** [comment]
> What are you trying to achieve? What commands/errors do you want to retry?

This feature would allow us to auto-retry on some idempotent commands(read-only commands like get/mget/... etc) instead of retrying all commands when timeout

**Comment by git-hulk** [comment]
@vmihailenco any thoughts about this PR?

**Comment by vmihailenco** [comment]
@git-hulk the presence of `dummyWatchCommand` suggests that the API is not quite right. E.g. it is not clear what to do about pipelines (this API accepts single cmd).

Overall this looks like a rate problem without an elegant solution. Which it adds some maintenance burden. I don't think such PRs should be merged.

**Comment by git-hulk** [comment]
okay, close the PR

**Pull request closed without merging**
