### PR TITLE
feat: add support for SINTERCARD command

### LINKED ISSUE #2289: Add support for SINTERCARD command
I didn't see `SinterCard` command(https://redis.io/commands/sintercard) in `go-redis`, Is there any particular reason for not supporting this?  if not, I'd happy to make contributions. I've finished coding and unit test.

### PR DESCRIPTION
**Pull request by boatrainlsz**
resolve #2289

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks

**Comment by boatrainlsz** [comment]
@vmihailenco Thanks for reviewing, when would be the next release? I'm actually in much need of this feature in next version.:smiley:

**Comment by vmihailenco** [comment]
@boatrainlsz I will tag v9.0.0-rc.2

**Comment by boatrainlsz** [comment]
> @boatrainlsz I will tag v9.0.0-rc.2

much appreciated

**Pull request merged**
