### PR TITLE
merge master and follow to golang-lint 1.40

### PR DESCRIPTION
**Pull request by monkey92t**
keep v9 branch and master branch in sync

### CODE REVIEW

**Review by vmihailenco — APPROVED** [review]

**Comment by vmihailenco** [comment]
@monkey92t you should have perms to merge PRs, right? If so - feel free to do so.

**Comment by monkey92t** [comment]
No, I don’t have any permissions

**Comment by vmihailenco** [comment]
@monkey92t strange - I've sent you an invite again. Please check your email.

**Comment by monkey92t** [comment]
OK, thanks!

**Pull request merged**
