### PR TITLE
Fix/pubsub ping mutex

### PR DESCRIPTION
**Pull request by vmihailenco**
Fixes https://github.com/go-redis/redis/issues/1874

### CODE REVIEW

**Comment by monkey92t** [comment]
I seem to have a misunderstanding, reading resp does not need to lock....let me add related tests

**Comment by vmihailenco** [comment]
>I seem to have a misunderstanding, reading resp does not need to lock....let me add related tests

We want to allow creating/removing subscriptions when reading messages. Otherwise `ReceiveTimeout` would hold the lock almost all the time.

**Comment by monkey92t** [comment]
Yes, I have a deadlock here....😭

**Comment by YongJieYongJie** [comment]
Thanks @monkey92t  @vmihailenco for extremely fast fix!

**Pull request merged**
