### PR TITLE
PubSub#Channel*(): allow to customize the timeout

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@N-o-X What about this solution for our problem?

**Comment by vmihailenco** [comment]
Any details why you need custom ping timeout?

**Comment by Al2Klimov** [comment]
To set it as high as possible not to run into it at all not to have to allocate huge channels.

**Comment by vmihailenco** [comment]
The API is already bloated and I don't believe many people need customizable ping timeout. I am fine with increasing ping timeout to 1 minute if that helps.

**Pull request closed without merging**
