### PR TITLE
fix when go-redis connect to ssdb server error

### PR DESCRIPTION
**Pull request by heipacker**
ssdb server link: https://github.com/ideawu/ssdb

when go-redis connect to ssdb server, and then do ping cmd, then ssdb server will reply *1(ArrayReply  = '*'), but this code cannot not parse this reply, 
```
cmd.val, cmd.err = cn.Rd.ReadStringReply()
return cmd.err
```
so i fix it by add below code:

```
val, err := cn.Rd.ReadReply(sliceParser)
	if err != nil {
		return err
	}
	if b, ok := val.([]byte); ok {
		// Bytes must be copied, because underlying memory is reused.
		cmd.val = string(b)
	}
	return nil
```

### CODE REVIEW

**Comment by vmihailenco** [comment]
I just tried following code and it works:

```
package main

import (
	"fmt"

	goredis "github.com/go-redis/redis"
)

func main() {
	redis := goredis.NewClient(&goredis.Options{
		Addr: ":8888",
	})

	fmt.Println(redis.Ping())
}
```

Could you show the code that reproduces this issue?

**Comment by heipacker** [comment]
redis-server is ok , but this statution is connect to ssdb server,  you can look  here  https://github.com/ideawu/ssdb

**Comment by vmihailenco** [comment]
Yes, I am connecting to SSDB at `localhost:8888`. Everything works fine.

**Comment by heipacker** [comment]
did you set password on ssdb?

**Comment by vmihailenco** [comment]
I just tried to set pasword and it is still working. Probably you are using old version. Try to update

```
go get -u github.com/go-redis/redis
```

and make sure you import `github.com/go-redis/redis`

**Comment by heipacker** [comment]
still has this error

ssdb version: 1.9.4

go-redis version: 
2fb3f0e45fb2c55d79dd7e4b06b5281ae437debb

and it checked , find this version is the newest one

my code
```go
	instConfig := config.Instances[dbName]
	client := redis.NewClient(&redis.Options{
		Addr:     instConfig.Url,
		Password: instConfig.Password, // no password set
		DB:       0,                   // use default DB
	})

	if pong, err := client.Ping().Result(); err != nil {
		log.Errorf("ping cache error %v", err)
		return nil, err
	} else {
		log.Infof("ping cache %v", pong)
	}

	return &Cache{
		Config: config,
		Client: client,
	}, nil

```


below is my log
```
[ERROR] [2017-07-31 20:02:59] [cache.go:23] - ping cache error redis: can't parse string reply: "*1"
[ERROR] [2017-07-31 20:02:59] [cache.go:53] - init cache redis1 error: redis: can't parse string reply: "*1"
panic: init database error

goroutine 82 [running]:
gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/common/cache.(*Caches).GetCache(0xc4201718c0, 0xaa4f0a, 0x6, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/common/cache/cache.go:54 +0x304
main.(*CacheModel).GetListAll(0xc4201aaa40, 0x69d5e9, 0x7fdbda726000, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/cache_model.go:33 +0x5c
main.(*Model).GetListAll(0xc4201aaa50, 0xc4201b6540, 0x7fdbda686fc0, 0xc4201c67e0, 0x0, 0xc4203b98c0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/model.go:30 +0x35
main.(*PlayerServer1).GetListAll(0xc420171cc8, 0x7fdbda686fc0, 0xc4201c67e0, 0xe42678, 0x0, 0x0, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/p1.go:20 +0xd4
gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/proto/player._S_GetListAll_Handler.func1(0x7fdbda686fc0, 0xc4201c67e0, 0xa0c280, 0xe42678, 0x1b, 0x7fdbda686fc0, 0xc4201c67e0, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/proto/player/player.pb.go:1221 +0x86
gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xlsoa/service.(*oAuthGuardian).UnaryServerInterceptor.func1(0x7fdbda686fc0, 0xc4201c6510, 0xa0c280, 0xe42678, 0xc4201b6340, 0xc4201b6360, 0xc4200156f0, 0xc4200359d8, 0x410ba8, 0x50)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xlsoa/service/oauth_guardian.go:77 +0xce
gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/proto/player._S_GetListAll_Handler(0xa76ae0, 0xc420171cc0, 0x7fdbda686fc0, 0xc4201c6510, 0xc4200d0460, 0xc4201ab000, 0x0, 0x0, 0x0, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/gitlab.xunlei.cn/xllive/proto/player/player.pb.go:1223 +0x177
gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200afcc0, 0xde95e0, 0xc420242840, 0xc4201c4500, 0xc4201a1a40, 0xe1e060, 0xc4201c6570, 0x0, 0x0)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc/server.go:781 +0xc41
gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200afcc0, 0xde95e0, 0xc420242840, 0xc4201c4500, 0xc4201c6570)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc/server.go:981 +0x15a6
gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4201cd080, 0xc4200afcc0, 0xde95e0, 0xc420242840, 0xc4201c4500)
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc/server.go:551 +0xa9
created by gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/root1/golang/gopkg/src/gitlab.xunlei.cn/xllive/player/vendor/google.golang.org/grpc/server.go:552 +0xa1

```

**Comment by vmihailenco** [comment]
What is the output of:

```
package main

import (
	"fmt"
	"net"
)

func main() {
	cn, err := net.Dial("tcp", ":8888")
	if err != nil {
		panic(err)
	}

	_, err = cn.Write([]byte("*1\r\n$4\r\nPING\r\n"))
	if err != nil {
		panic(err)
	}

	b := make([]byte, 1024)
	n, err := cn.Read(b)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(b[:n]))
}
```

**Comment by heipacker** [comment]
output:
-NOAUTH authentication required

**Comment by vmihailenco** [comment]
Disable authentication in SSDB and try again.

**Comment by heipacker** [comment]
output:
+PONG

**Comment by vmihailenco** [comment]
That is the reply from SSDB and it does not contain `1(ArrayReply = '')`. You need to find out how you are getting such response from SSDB.

**Comment by heipacker** [comment]
```
20:59:03.946288 IP (tos 0x0, ttl 64, id 58574, offset 0, flags [DF], proto TCP (6), length 105)
    10.0.1.74.46872 > 10.10.45.82.8888: Flags [P.], cksum 0xc530 (correct), seq 1:54, ack 1, win 229, options [nop,nop,TS val 40206245 ecr 806596896], length 53
	0x0000:  4500 0069 e4ce 4000 4006 131b 0a00 014a  E..i..@.@......J
	0x0010:  0a0a 2d52 b718 22b8 4bc9 9b6f a0e3 4652  ..-R..".K..o..FR
	0x0020:  8018 00e5 c530 0000 0101 080a 0265 7fa5  .....0.......e..
	0x0030:  3013 b120 2a32 0d0a 2434 0d0a 6175 7468  0...*2..$4..auth
	0x0040:  0d0a 2433 320d 0a4b 6c76 6e62 676e 6577  ..$32..Klvnbgnew
	0x0050:  6572 4576 616e 4f76 5475 5769 5175 6f62  erEvanOvTuWiQuob
	0x0060:  6b32 3261 6976 350d 0a                   k22aiv5..
20:59:03.952220 IP (tos 0x0, ttl 62, id 63348, offset 0, flags [DF], proto TCP (6), length 52)
    10.10.45.82.8888 > 10.0.1.74.46872: Flags [.], cksum 0x277c (correct), seq 1, ack 54, win 227, options [nop,nop,TS val 806596902 ecr 40206245], length 0
	0x0000:  4500 0034 f774 4000 3e06 02aa 0a0a 2d52  E..4.t@.>.....-R
	0x0010:  0a00 014a 22b8 b718 a0e3 4652 4bc9 9ba4  ...J".....FRK...
	0x0020:  8010 00e3 277c 0000 0101 080a 3013 b126  ....'|......0..&
	0x0030:  0265 7fa5                                .e..
20:59:03.952559 IP (tos 0x0, ttl 62, id 63349, offset 0, flags [DF], proto TCP (6), length 63)
    10.10.45.82.8888 > 10.0.1.74.46872: Flags [P.], cksum 0x83e5 (correct), seq 1:12, ack 54, win 227, options [nop,nop,TS val 806596902 ecr 40206245], length 11
	0x0000:  4500 003f f775 4000 3e06 029e 0a0a 2d52  E..?.u@.>.....-R
	0x0010:  0a00 014a 22b8 b718 a0e3 4652 4bc9 9ba4  ...J".....FRK...
	0x0020:  8018 00e3 83e5 0000 0101 080a 3013 b126  ............0..&
	0x0030:  0265 7fa5 2a31 0d0a 2431 0d0a 310d 0a    .e..*1..$1..1..
20:59:03.952573 IP (tos 0x0, ttl 64, id 58575, offset 0, flags [DF], proto TCP (6), length 52)
    10.0.1.74.46872 > 10.10.45.82.8888: Flags [.], cksum 0x276d (correct), seq 54, ack 12, win 229, options [nop,nop,TS val 40206247 ecr 806596902], length 0
	0x0000:  4500 0034 e4cf 4000 4006 134f 0a00 014a  E..4..@.@..O...J
	0x0010:  0a0a 2d52 b718 22b8 4bc9 9ba4 a0e3 465d  ..-R..".K.....F]
	0x0020:  8010 00e5 276d 0000 0101 080a 0265 7fa7  ....'m.......e..
	0x0030:  3013 b126                                0..&
20:59:13.267145 IP (tos 0x0, ttl 64, id 30794, offset 0, flags [DF], proto TCP (6), length 52)
    10.0.1.74.37834 > 10.10.45.82.8888: Flags [F.], cksum 0xc2cb (correct), seq 0, ack 1, win 229, options [nop,nop,TS val 40208576 ecr 803163320], length 0
	0x0000:  4500 0034 784a 4000 4006 7fd4 0a00 014a  E..4xJ@.@......J
	0x0010:  0a0a 2d52 93ca 22b8 bd60 1ef4 d761 fe6f  ..-R.."..`...a.o
	0x0020:  8011 00e5 c2cb 0000 0101 080a 0265 88c0  .............e..
	0x0030:  2fdf 4cb8                                /.L.

```

from this dump, can find the *1..$1..1.. is return by auth cmd

**Comment by heipacker** [comment]
too strange, i change a new ssdb server, is ok.

**Pull request closed without merging**
