### PR TITLE
fix NewConnPool checkMinIdleConns data race

### PR DESCRIPTION
**Pull request by lwightmoon**

### CODE REVIEW

**Comment by vmihailenco** [comment]
`NewConnPool` is by definition race free - only one goroutine has access to the pool while it is created.

**Comment by lwightmoon** [comment]
checkMinIdleConns is not safe ,may add lock when called in NewConnPool

**Comment by lwightmoon** [comment]
> `NewConnPool` is by definition race free - only one goroutine has access to the pool while it is created.

checkMinIdleConns is not safe ,may add lock when called in NewConnPool
image

**Comment by theoptz** [comment]
+1

**Comment by vmihailenco** [comment]
See https://github.com/go-redis/redis/pull/1315#issuecomment-621644965 - I think there can not be a race here.

**Pull request merged**
