### PR TITLE
Migrated tests to ginkgo/gomega

### PR DESCRIPTION
**Pull request by dim**

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can you please fix Travis:

```
0.23s$ go get onsi.github.io/ginkgo

package onsi.github.io/ginkgo: unrecognized import path "onsi.github.io/ginkgo"

The command "go get onsi.github.io/ginkgo" failed and exited with 1 during .
```

**Comment by dim** [comment]
Sure, pushed

**Comment by dim** [comment]
Any idea why sentinel tests were/are failing with an EOF?

**Comment by vmihailenco** [comment]
Don't know for sure, but most likely Redis is not killed properly. Also you probably have to revert Makefile changes in order to run tests on Travis.

**Comment by vmihailenco** [comment]
@dim I just gave you permissions to create branches in this repo. Can you please create branch in this repo and open new PR so I can try to help you with Travis?

**Comment by dim** [comment]
Pushed https://github.com/go-redis/redis/tree/feature/ginkgo-suite, don't think it's to do with Redis not being killed, as I added a check for that in https://github.com/go-redis/redis/blob/feature/ginkgo-suite/sentinel_test.go#L56, plus I am even waiting for a slave to become the master in https://github.com/go-redis/redis/blob/feature/ginkgo-suite/sentinel_test.go#L61

**Comment by dim** [comment]
Closing in favour of https://github.com/go-redis/redis/pull/63

**Pull request closed without merging**
