### PR TITLE
Extract pool package. Add pool benchmark.

### PR DESCRIPTION
**Pull request by vmihailenco**
@dim I extracted pool implementation to separate package so I can properly benchmark connection removal. And I can't notice any slowdown on big pools (1000 connections).

```
BenchmarkPoolGetPut10Conns-4     	 5000000	       287 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetPut100Conns-4    	 5000000	       284 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetPut1000Conns-4   	 5000000	       246 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetRemove10Conns-4  	  300000	      3913 ns/op	    8416 B/op	       7 allocs/op
BenchmarkPoolGetRemove100Conns-4 	  300000	      3979 ns/op	    8416 B/op	       7 allocs/op
BenchmarkPoolGetRemove1000Conns-4	  300000	      3859 ns/op	    8416 B/op	       7 allocs/op
```

### CODE REVIEW

**Comment by dim** [comment]
Thanks, I was about to ask for this

**Comment by dim** [comment]
Hmm, I'm getting:

```
$ go test ./... -test.run=NONE -test.bench=Pool -test.benchmem
PASS
BenchmarkPoolGetPut10Conns-4     	 5000000	       403 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetPut100Conns-4    	 3000000	       396 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetPut1000Conns-4   	 5000000	       394 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolGetRemove10Conns-4  	--- FAIL: BenchmarkPoolGetRemove10Conns-4
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
BenchmarkPoolGetRemove100Conns-4 	--- FAIL: BenchmarkPoolGetRemove100Conns-4
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
BenchmarkPoolGetRemove1000Conns-4	--- FAIL: BenchmarkPoolGetRemove1000Conns-4
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
	bench_test.go:329: no error expected on pool.Remove but received: redis: you open connections too fast (last_error="benchmark")
```

**Comment by vmihailenco** [comment]
Yeah, I manually add `if false && p.rl.Limit() {` to disable rate limiter. Thinking how to fix it...

**Comment by vmihailenco** [comment]
Added fix to https://github.com/go-redis/redis/pull/275

**Pull request merged**
