### PR TITLE
Fix PubSub panic on concurrent Close.

### PR DESCRIPTION
**Pull request by vmihailenco**
Replaces https://github.com/go-redis/redis/pull/199

### CODE REVIEW

**Comment by vmihailenco** [comment]
@shagabutdinov for some reason github can't link commit to your account... Do you know how I can fix it?

**Comment by shagabutdinov** [comment]
Thank you for making test! Next time I'll ask you how to test whole thing before opening PR. I have a question for private error: if close error is private, how it is possible to check if error occured because of pubsub was closed; code example:

```
for {
  message, err := subscribe.ReceiveMessage()
  if _, ok := err.(redis.CloseError) {
    break
  }

  if err != nil {
    panic(err)
    return
  }

  // process message here
}
```

I suppose it could be done by error message, but error message will be changed more likely than error type.

**Comment by vmihailenco** [comment]
So far the plan is to implement `net.Error.Temporary` interface as described in https://github.com/go-redis/redis/issues/193#issuecomment-158911028. But I did not have time to give it a proper thought.

**Comment by shagabutdinov** [comment]
> @shagabutdinov for some reason github can't link commit to your account... Do you know how I can fix it?

I think I should attach extra email that I use for work and github will fix it automatically. 

> So far the plan is to implement net.Error.Temporary interface as described in #193 (comment). But I did not have time to give it a proper thought.

Ok, got it.

**Pull request merged**
