### PR TITLE
Add ParseURL function for cluster mode

### PR DESCRIPTION
**Pull request by stephaniehingtgen**
**What this PR does**
This PR adds a new function, `ParseClusterURL`, which takes a string and turns it into the array of addresses used for redis in cluster mode along with configurations passed in.

**How it works**
It is very similar to the `ParseURL` function, except for this function only allows for the `redis` and `rediss` schemes and will take one to many `addr` parameters. It will get the username and password for the cluster as well as configurations sent in through the query parameters.

Examples that will succeed:
```
"rediss://foo:bar@localhost:6378?read_timeout=1s&addr=localhost:6379"
"redis://foo:bar@localhost:6378?read_timeout=1s&addr=localhost:6379&addr=localhost:6380"
```

Examples that will fail:
```
"redis://foo:bar@localhost:6378?read_timeout=1s&addr=localhost:6379&addr=redis://localhost:6380" // cannot use scheme again in params
"localhost:6378?read_timeout=1s&addr=localhost:6379&addr=localhost:6380" // must use redis or rediss scheme
```

### CODE REVIEW

**Comment by stephaniehingtgen** [comment]
👋 Hey, @vmihailenco, just wanted to follow up and see if you had any further comments on this PR?

**Comment by vmihailenco** [comment]
@stephaniehingtgen this looks good, but I need some time to experiment with options API first before we merge this PR and make it available for everyone. Sorry for the delay and thanks for your work :+1:

**Comment by scotchneat** [comment]
Excited to see this.

One comment regarding the URL format was that I would have expected the list of hosts to be a comma-delimited list in the host part of the URL (like a [mongo uri](https://docs.mongodb.com/manual/reference/connection-string/))

`rediss://user:pass@host1:6379,host2:6380,host3:6381?sslmode=verify-full&connect_timeout=10`

This would allow the query parameters to map to connection configuration options.

**Comment by jrots** [comment]
Great stuff, any chance that this could get merged? In need of TLS support when connecting to an elisticache redis cluster here.. 😇

**Comment by stephaniehingtgen** [comment]
> Excited to see this.
> 
> One comment regarding the URL format was that I would have expected the list of hosts to be a comma-delimited list in the host part of the URL (like a [mongo uri](https://docs.mongodb.com/manual/reference/connection-string/))
> 
> `rediss://user:pass@host1:6379,host2:6380,host3:6381?sslmode=verify-full&connect_timeout=10`
> 
> This would allow the query parameters to map to connection configuration options.

I'd be happy to make this change! I'd just like to wait to get the go ahead from @vmihailenco before continuing work on this PR. If this PR is going to be used, then I will make that change asap :)

**Pull request merged**
