### PR TITLE
Internalise rate-limiter

### PR DESCRIPTION
**Pull request by dim**
Given that this lib is widely used, it's probably worth avoiding external dependencies, especially since it's only a few LOC.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Probably it should be in vendor/ folder? I don't have much experience with using vendor in libraries...

**Comment by dim** [comment]
So no, that's not how vendor/ works. I think using internal is most appropriate here

**Comment by vmihailenco** [comment]
Can you please fix/disable this test? If fails every 2nd time I retry build.

```
• Failure [0.110 seconds]

RateLimiter

/home/travis/gopath/src/gopkg.in/redis.v4/internal/ratelimit/ratelimit_test.go:116

  should correctly spread allowance [It]

  /home/travis/gopath/src/gopkg.in/redis.v4/internal/ratelimit/ratelimit_test.go:61

  Expected

      <int>: 50

  to be ~

      <int>: 54
```

**Comment by vmihailenco** [comment]
I removed rate limiter from dialer, because it was rarely useful but caused a lot of confusion. Closing this PR.

**Pull request closed without merging**
