### PR TITLE
Remove OpenTelemetry metrics for now

### PR DESCRIPTION
**Pull request by vmihailenco**
Fixes https://github.com/go-redis/redis/issues/1534

Removing metrics for now since they should use a ValueRecorder that records operation durations (if I remember Otel terms correctly)...

### CODE REVIEW

**Comment by pierrre** [comment]
I think you should also update go.mod/go.sum, with `go mod tidy`.
So it won't reference it anymore.

**Comment by vmihailenco** [comment]
@pierrre done, thanks

**Review by monkey92t — APPROVED** [review]

**Comment by monkey92t** [comment]
Do we need to release a new version?

**Comment by vmihailenco** [comment]
@monkey92t yes, I think so. Could you tag one please?

**Comment by monkey92t** [comment]
@vmihailenco OK, let me do it

**Comment by pierrre** [comment]
Do you plan to tag it today ?
(It's my last day at my job, and I want to fix this issue :sweat_smile: )
Thank you :+1:

**Comment by monkey92t** [comment]
@pierrre I have created v8.11.0 version, I forgot to modify CHANGELOG.md, I will add it later.

**Comment by pierrre** [comment]
Thank you, it works !
FYI I had to manually change the version in `go.mod` to `v8.11.0`, before updating other dependencies.

**Pull request merged**
