### PR TITLE
a simple redis client mock

### PR DESCRIPTION
**Pull request by monkey92t**
it can help unit testing in a simple environment. not used as `redis.client` basic code,  added to `extra` for reference.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can we move this to a separate repository so it can be developed & updated separately? I can create a repo in go-redis org or you can create a repo under your account. Anyway I will a link to the readme so people can discover and use it.

**Comment by monkey92t** [comment]
> Can we move this to a separate repository so it can be developed & updated separately? I can create a repo in go-redis org or you can create a repo under your account. Anyway I will a link to the readme so people can discover and use it.

good way, we can create a repo go-redis/mock, support v7 and v8 version in a short time.

**Comment by vmihailenco** [comment]
Good, I've created https://github.com/go-redis/redismock and sent you an invite.

**Comment by vmihailenco** [comment]
@monkey92t I've added a link to the Readme and pinged everyone at Discord. Let me know if there is anything else I can do.

**Pull request closed without merging**
