### PR TITLE
cluster: release reloading with delay.

### PR DESCRIPTION
**Pull request by vmihailenco**
/cc @dim 

See comment for details.

### CODE REVIEW

**Comment by vmihailenco** [comment]
@dim ping

**Comment by dim** [comment]
Sorry, busy recently :) I'm no a big fan of artificial delays but the only alternative solution I can think of is a background channel-select loop, where a `c.reloading <- struct{}{}` channel is triggering a reload.

**Comment by vmihailenco** [comment]
How that would help? The problem here is that sequence
- start processing command
- get hash slot
- slot moved - reloading
- finish processing

is not synchronized and we can't tell if we need to reload slots or there was a race between reloading and command processing.

**Comment by dim** [comment]
Sorry, I thought the problem was that:

1. start processing command #1
2. get hash slot, MOVED
3. trigger reloading
4. start processing command #2
5. get hash slot, MOVED
6. trigger reloading again

I don't quite understand what you mean by:
> there was a race between reloading and command processing

**Comment by vmihailenco** [comment]
The sequence is:

- cmd1: start processing command
- cmd1: get hash slot
- cmd1: MOVED
- cmd1: trigger reloading
- cmd2: start processing command #2
- cmd2: get hash slot
- cmd1: reloading finished
- cmd2: MOVED
- cmd2: trigger reloading

So there is a race between `cmd1: reloading finished` and `cmd2: trigger reloading`.

**Comment by vmihailenco** [comment]
@dim ping

**Comment by dim** [comment]
I think adding a 1s delay will cause more problems than it solves. You could have a genuine slot reallocation by redis in the meantime. I don't see the 'race' being much on an issue, it will trigger another slot sync, but is this really causing much overhead? I don't believe we will even end up in a spinning state. If you are really keen to avoid it, why don't compare you compare `addr` returned by `isMovedError` against  the stored address for that slot? Then, you would only trigger `lazyReloadSlots` if they are different.

As said, I really don't like artificial delays, they always tend to cause not trivial issues downstream.

**Comment by vmihailenco** [comment]
@dim done. PTAL

**Comment by vmihailenco** [comment]
@dim gentle ping. I think I addressed your comment.

**Comment by dim** [comment]
@vmihailenco really sorry, been pretty busy, LGTM now

**Pull request merged**
