### PR TITLE
Properly pass username/password in Sentinel

### LINKED ISSUE #1447: UniversalClient fails authentication against password protected Sentinel
I'm running Redis v6.0.5 Sentinel cluster (from bitnami/redis) and using UniversalClient.
The MasterName and Password fields in redis.UniversalOptions{} are properly set.
I'm seeing the following error when trying to connect:
```
redis: 2020/08/20 01:31:03 sentinel.go:396: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required.
```

### PR DESCRIPTION
**Pull request by dmitsh**
Fixes #1447

Signed-off-by: Dmitry Shmulevich <dmitry.shmulevich@sysdig.com>

### CODE REVIEW

**Comment by dmitsh** [comment]
I tested this PR against password-protected Redis Sentinel, and it worked fine.

**Comment by vmihailenco** [comment]
AFAIK separate fields are needed when Sentinel uses different password. Perhaps you can set `SentinelUsername` and `SentinelPassword` in https://github.com/go-redis/redis/blob/master/universal.go#L102?

**Comment by dmitsh** [comment]
@vmihailenco , thanks, good catch. I didn't realize Sentinel might have its own password:

**Comment by dmitsh** [comment]
@vmihailenco , I've restored SentinelPassword. Looking at documentation I don't see that SentinelUsername is used for Sentinel authentication. The only setting in Sentinel configuration is `requirepass <password>`.

**Comment by vmihailenco** [comment]
Thanks!

**Comment by mahanam** [comment]
Hi,

I faced the issue again as mentioned above.

Below is the code snippet
    rdb = redis.NewUniversalClient(&redis.UniversalOptions{
            MasterName:    "mymaster",
            Addrs:      []string{"redis-ha:26379"},
            Username: "redis",
            Password: "yoC4a4DLPB",
            //MaxRetries:       10,
            //DialTimeout:  10 * time.Second,
            //ReadTimeout:  30 * time.Second,
            //WriteTimeout: 30 * time.Second,
            //PoolSize:     10,
            //PoolTimeout:  30 * time.Second,
            DB: 0,
    })

Kindly could you please let us know if this is not the approach.

Thanks,
Mahadev

**Comment by dmitsh** [comment]
@mahanam, not sure I understand the question.
What error are you getting? Can you operate from redis-cli? How do you authenticate from redis-cli?

**Comment by mahanam** [comment]
Hi,

Am facing the below error, 

root@redis-ha-client-1:/data# go run mredis.go
redis: 2020/08/31 05:24:54 sentinel.go:396: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required.
2020/08/31 05:24:54 Connection failed with redis master serverredis: all sentinels are unreachable
exit status 1

#####################################################
package main

import (
    "context"
    "log"
    "github.com/go-redis/redis/v8"
)

var (
    ctx = context.Background()
)


func main() {
    NewRedisClient()
}


func NewRedisClient() {
    //var client *redis.Cli ent
    var rdb redis.UniversalClient
    rdb = redis.NewUniversalClient(&redis.UniversalOptions{
            MasterName:    "mymaster",
            Addrs:         []string{"redis-ha:26379"},
            Username: "redis",
            Password: "yoC4a4DLPB",
            //MaxRetries:       10,
            //DialTimeout:  10 * time.Second,
            //ReadTimeout:  30 * time.Second,
            //WriteTimeout: 30 * time.Second,
            //PoolSize:     10,
            //PoolTimeout:  30 * time.Second,
            DB: 0,
    })

    _, err := rdb.Ping(ctx).Result()
    if err != nil {
        log.Fatal("COnnection failed with redis master server", err)
    }

    log.Print("Successfully connected to the redis master server:")

}


But when i do with FailoverClient it works on the same setup.
root@redis-ha-client-1:/data# go run mredis.go
redis: 2020/08/31 05:28:41 sentinel.go:470: sentinel: discovered new sentinel="8aa9e5a01e335c67fd47d27828e72ef0331832b1" for master="mymaster"
redis: 2020/08/31 05:28:41 sentinel.go:470: sentinel: discovered new sentinel="be4a58fb9643a5d7eafb0a3a27fa135b3116ab60" for master="mymaster"
redis: 2020/08/31 05:28:41 sentinel.go:470: sentinel: discovered new sentinel="de64ed179ae569c599d8a64f993188ff7cee1ec1" for master="mymaster"
redis: 2020/08/31 05:28:46 sentinel.go:438: sentinel: new master="mymaster" addr="10.233.112.15:6379"
2020/08/31 05:28:46 Successfully connected to the redis master server:

Code snippet, Just replaced with NewFailoverClient and it works
    rdb = redis.NewFailoverClient(&redis.FailoverOptions{
            MasterName:    "mymaster",
            SentinelAddrs: []string{"redis-ha:26379"},
            SentinelPassword: "yoC4a4DLPB",
            Password: "yoC4a4DLPB",
            MaxRetries:       10,
            DB: 0,
        })

**Comment by dmitsh** [comment]
@mahanam , could you try the fix in #1456?

**Comment by mahanam** [comment]
Thanks! It worked

By when this fix will be released ?

**Comment by dmitsh** [comment]
> Thanks! It worked
> 
> By when this fix will be released ?

I'm not a maintainer, so I don't know. Hopefully soon :)

**Pull request merged**
